/**
 * SafeStep Export Service
 * Client-side PDF and ZIP generation for evidence logs.
 * Uses jsPDF for PDF and JSZip for ZIP packaging.
 */

import { jsPDF } from 'jspdf';
import JSZip from 'jszip';

/**
 * Generate a PDF evidence log for a case.
 * Contains: file list, SHA-256 hashes, timestamps, and case metadata.
 * @param {object} caseData - Case object
 * @param {Array} evidenceItems - Array of evidence records
 * @returns {Blob} PDF file as a Blob
 */
export function generateEvidenceLogPdf(caseData, evidenceItems) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Helper to add page break if needed
  const checkPageBreak = (neededSpace = 30) => {
    if (y + neededSpace > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // ──── Header ────
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SafeStep — Evidence Log', margin, y);
  y += 10;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text(
    'SafeStep provides general information only and is not a substitute for legal advice.',
    margin,
    y
  );
  doc.setTextColor(0);
  y += 10;

  // ──── Divider ────
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // ──── Case Info ────
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Case Information', margin, y);
  y += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const caseInfo = [
    `Case ID: ${caseData.id}`,
    `Category: ${caseData.categoryId || 'Not specified'}`,
    `Created: ${formatDate(caseData.createdAt)}`,
    `Export Date: ${formatDate(new Date().toISOString())}`,
    `Total Evidence Items: ${evidenceItems.length}`,
  ];
  caseInfo.forEach(line => {
    doc.text(line, margin, y);
    y += 5;
  });
  y += 5;

  // ──── Evidence Items ────
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Evidence Items', margin, y);
  y += 10;

  if (evidenceItems.length === 0) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.text('No evidence items recorded.', margin, y);
    y += 7;
  } else {
    evidenceItems.forEach((item, index) => {
      checkPageBreak(45);

      // Item number
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${item.fileName}`, margin, y);
      y += 6;

      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');

      const details = [
        `File Type: ${item.fileType}`,
        `File Size: ${formatFileSize(item.fileSize)}`,
        `SHA-256 Hash: ${item.hash}`,
        `Uploaded: ${formatDate(item.createdAt)}`,
      ];

      if (item.description) {
        details.push(`Description: ${item.description}`);
      }

      if (item.deviceMetadata?.timezone) {
        details.push(`Timezone: ${item.deviceMetadata.timezone}`);
      }

      details.forEach(detail => {
        // Wrap long lines
        const lines = doc.splitTextToSize(detail, contentWidth - 5);
        lines.forEach(line => {
          checkPageBreak(6);
          doc.text(line, margin + 5, y);
          y += 4.5;
        });
      });

      y += 5;

      // Separator between items
      if (index < evidenceItems.length - 1) {
        doc.setDrawColor(230);
        doc.line(margin + 5, y, pageWidth - margin - 5, y);
        y += 5;
      }
    });
  }

  // ──── Footer ────
  checkPageBreak(25);
  y += 5;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(120);
  const footer = [
    'This document was generated by SafeStep and records evidence preserved by the user.',
    'SHA-256 hashes verify file integrity — if a file\'s hash matches, it has not been modified since upload.',
    'This log does not constitute legal certification. Consult a lawyer for admissibility guidance.',
    `Generated: ${new Date().toISOString()}`,
  ];
  footer.forEach(line => {
    doc.text(line, margin, y);
    y += 4;
  });

  return doc.output('blob');
}

/**
 * Generate a ZIP package containing evidence files and a manifest.
 * @param {object} caseData - Case object
 * @param {Array} evidenceItems - Array of evidence records (with file data)
 * @returns {Promise<Blob>} ZIP file as a Blob
 */
export async function generateEvidenceZip(caseData, evidenceItems) {
  const zip = new JSZip();

  // Add manifest
  const manifest = generateManifest(caseData, evidenceItems);
  zip.file('manifest.txt', manifest);

  // Add evidence files
  for (const item of evidenceItems) {
    if (item.fileData) {
      zip.file(`evidence/${item.fileName}`, item.fileData);
    }
  }

  // Add a README
  zip.file('README.txt', [
    'SafeStep Evidence Export',
    '========================',
    '',
    'This ZIP contains evidence files and a manifest with SHA-256 hashes and timestamps.',
    '',
    'IMPORTANT:',
    '- The manifest.txt file contains SHA-256 hashes for each evidence file.',
    '- You can verify file integrity by computing the SHA-256 hash and comparing it to the manifest.',
    '- This export does not constitute legal certification.',
    '- Consult a qualified lawyer for guidance on evidence admissibility.',
    '',
    'SafeStep provides general information only and is not a substitute for legal advice.',
    '',
    `Export Date: ${new Date().toISOString()}`,
  ].join('\n'));

  return zip.generateAsync({ type: 'blob' });
}

/**
 * Generate a plain-text manifest for the evidence.
 */
function generateManifest(caseData, evidenceItems) {
  const lines = [
    '╔══════════════════════════════════════════════════╗',
    '║        SafeStep — Evidence Manifest              ║',
    '╚══════════════════════════════════════════════════╝',
    '',
    `Case ID:        ${caseData.id}`,
    `Category:       ${caseData.categoryId || 'Not specified'}`,
    `Created:        ${formatDate(caseData.createdAt)}`,
    `Export Date:    ${formatDate(new Date().toISOString())}`,
    `Total Files:    ${evidenceItems.length}`,
    '',
    '─'.repeat(60),
    '',
  ];

  evidenceItems.forEach((item, index) => {
    lines.push(`[${index + 1}] ${item.fileName}`);
    lines.push(`    Type:       ${item.fileType}`);
    lines.push(`    Size:       ${formatFileSize(item.fileSize)}`);
    lines.push(`    SHA-256:    ${item.hash}`);
    lines.push(`    Uploaded:   ${formatDate(item.createdAt)}`);
    if (item.description) {
      lines.push(`    Note:       ${item.description}`);
    }
    lines.push('');
  });

  lines.push('─'.repeat(60));
  lines.push('');
  lines.push('DISCLAIMER: SafeStep provides general information only.');
  lines.push('This manifest does not constitute legal certification.');
  lines.push('Consult a qualified lawyer for admissibility guidance.');

  return lines.join('\n');
}

// ──────────────────────── Helpers ────────────────────────

function formatDate(isoString) {
  try {
    const d = new Date(isoString);
    return d.toLocaleString('en-IN', {
      year: 'numeric',
      month: 'short',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      timeZoneName: 'short',
    });
  } catch {
    return isoString;
  }
}

function formatFileSize(bytes) {
  if (!bytes || bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}
